/* Generated by Yosys 0.8 (git sha1 UNKNOWN, clang 10.0.0 -fPIC -Os) */

(* top =  1  *)
(* src = "/Users/tramyn/Documents/workspaces/cello_workspace/yosysRun/contAssign2.v:8" *)
module contAssign2(a, b, y);
  wire _0_;
  wire _1_;
  (* src = "/Users/tramyn/Documents/workspaces/cello_workspace/yosysRun/contAssign2.v:10" *)
  input a;
  (* src = "/Users/tramyn/Documents/workspaces/cello_workspace/yosysRun/contAssign2.v:11" *)
  input b;
  (* src = "/Users/tramyn/Documents/workspaces/cello_workspace/yosysRun/contAssign2.v:12" *)
  output y;
  assign _0_ = ~a;
  assign _1_ = ~b;
  assign y = ~(_0_ | _1_);
endmodule
