/* Generated by Yosys 0.8 (git sha1 UNKNOWN, clang 10.0.0 -fPIC -Os) */

(* top =  1  *)
(* src = "/Users/tramyn/Documents/workspaces/cello_workspace/yosysRun/contAssign6.v:7" *)
module contAssign6(a, b, y);
  (* src = "/Users/tramyn/Documents/workspaces/cello_workspace/yosysRun/contAssign6.v:9" *)
  input a;
  (* src = "/Users/tramyn/Documents/workspaces/cello_workspace/yosysRun/contAssign6.v:10" *)
  input b;
  (* src = "/Users/tramyn/Documents/workspaces/cello_workspace/yosysRun/contAssign6.v:11" *)
  output y;
  assign y = ~(a | b);
endmodule
