/* Generated by Yosys 0.8 (git sha1 UNKNOWN, clang 10.0.0 -fPIC -Os) */

(* top =  1  *)
(* src = "/Users/tramyn/Documents/workspaces/cello_workspace/yosysRun/filter.v:4" *)
module Start_QS2in_QS1in_Sensor_QS2out_QS1out_Actuator_net(Start, QS2in, QS1in, Sensor, QS2out, QS1out, Actuator);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  (* src = "/Users/tramyn/Documents/workspaces/cello_workspace/yosysRun/filter.v:12" *)
  output Actuator;
  (* src = "/Users/tramyn/Documents/workspaces/cello_workspace/yosysRun/filter.v:8" *)
  input QS1in;
  (* src = "/Users/tramyn/Documents/workspaces/cello_workspace/yosysRun/filter.v:11" *)
  output QS1out;
  (* src = "/Users/tramyn/Documents/workspaces/cello_workspace/yosysRun/filter.v:7" *)
  input QS2in;
  (* src = "/Users/tramyn/Documents/workspaces/cello_workspace/yosysRun/filter.v:10" *)
  output QS2out;
  (* src = "/Users/tramyn/Documents/workspaces/cello_workspace/yosysRun/filter.v:9" *)
  input Sensor;
  (* src = "/Users/tramyn/Documents/workspaces/cello_workspace/yosysRun/filter.v:6" *)
  input Start;
  assign _00_ = ~Sensor;
  assign _04_ = ~(_01_ | _02_);
  assign _02_ = ~(QS1in | _04_);
  assign QS2out = ~_02_;
  assign _05_ = ~(_00_ | _01_);
  assign _01_ = ~(Start | _05_);
  assign QS1out = ~_01_;
  assign _06_ = ~(_02_ | _03_);
  assign _03_ = ~(QS2in | _06_);
  assign Actuator = ~_03_;
endmodule
