/* Generated by Yosys 0.8 (git sha1 UNKNOWN, clang 10.0.0 -fPIC -Os) */

(* top =  1  *)
(* src = "/Users/tramyn/Documents/workspaces/cello_workspace/yosysRun/contAssign4.v:7" *)
module contAssign4(a, b, y);
  wire _0_;
  (* src = "/Users/tramyn/Documents/workspaces/cello_workspace/yosysRun/contAssign4.v:9" *)
  input a;
  (* src = "/Users/tramyn/Documents/workspaces/cello_workspace/yosysRun/contAssign4.v:10" *)
  input b;
  (* src = "/Users/tramyn/Documents/workspaces/cello_workspace/yosysRun/contAssign4.v:11" *)
  output y;
  assign _0_ = ~(a | b);
  assign y = ~_0_;
endmodule
