/* Generated by Yosys 0.8 (git sha1 UNKNOWN, clang 10.0.0 -fPIC -Os) */


module r_s_q_sl_instance__state_net(r, s, q);
  wire _0_;
  wire _1_;
  output q;
  input r;
  input s;
  assign _1_ = ~(r | _0_);
  assign _0_ = ~(s | _1_);
  assign q = ~_0_;
endmodule
