// This verilog module was generated by ATACS to produce
// a synthesized circuitry of the evenzeroes.
//
// author: Tramy Nguyen
module bit1_bit0_parity1_parity0_ez_instance__state_net(bit1, bit0, parity1, parity0);

  input bit1;
  input bit0;
  output parity1;
  output parity0;
  wire ez_instance__state;

assign parity1 = (bit1 & ~ez_instance__state) | (bit0 & ~parity0 & ez_instance__state) | (bit0 & parity1);
assign parity0 = (bit1 & ez_instance__state) | (bit0 & parity0) | (bit0 & ~parity1 & ~ez_instance__state);
assign ez_instance__state = (parity0) | (~parity1 & ez_instance__state);

// Initial state:
// !bit1 !bit0 !parity1 !parity0 !ez_instance__state

endmodule
