/*******************************************************************************
 *  
 * This file is part of iBioSim. Please visit <http://www.async.ece.utah.edu/ibiosim>
 * for the latest version of iBioSim.
 *
 * Copyright (C) 2017 University of Utah
 *
 * This library is free software; you can redistribute it and/or modify it
 * under the terms of the Apache License. A copy of the license agreement is provided
 * in the file named "LICENSE.txt" included with this software distribution
 * and also available online at <http://www.async.ece.utah.edu/ibiosim/License>.
 *  
 *******************************************************************************/
/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package edu.utah.ece.async.lema.verification.lpn;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 * 
 * @author 
 * @author Chris Myers
 * @author <a href="http://www.async.ece.utah.edu/ibiosim#Credits"> iBioSim Contributors </a>
 * @version %I%
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DOT = 1;
  /** RegularExpression Id. */
  int ATACS = 2;
  /** RegularExpression Id. */
  int END = 3;
  /** RegularExpression Id. */
  int INPUTS = 4;
  /** RegularExpression Id. */
  int INIT_STATE = 5;
  /** RegularExpression Id. */
  int DUMMYS = 6;
  /** RegularExpression Id. */
  int FAILTRANS = 7;
  /** RegularExpression Id. */
  int VARIABLES = 8;
  /** RegularExpression Id. */
  int INTEGERS = 9;
  /** RegularExpression Id. */
  int NONINPS = 10;
  /** RegularExpression Id. */
  int KEEPS = 11;
  /** RegularExpression Id. */
  int ABSTRACTS = 12;
  /** RegularExpression Id. */
  int CONTINUOUS = 13;
  /** RegularExpression Id. */
  int RATES = 14;
  /** RegularExpression Id. */
  int INITRATES = 15;
  /** RegularExpression Id. */
  int INITVALS = 16;
  /** RegularExpression Id. */
  int INITINTS = 17;
  /** RegularExpression Id. */
  int INVARIANTS = 18;
  /** RegularExpression Id. */
  int ENABLINGS = 19;
  /** RegularExpression Id. */
  int ASSIGNS = 20;
  /** RegularExpression Id. */
  int TRANS_RATES = 21;
  /** RegularExpression Id. */
  int RATE_ASSIGNS = 22;
  /** RegularExpression Id. */
  int INT_ASSIGNS = 23;
  /** RegularExpression Id. */
  int DELAY_ASSIGNS = 24;
  /** RegularExpression Id. */
  int PRIORITY_ASSIGNS = 25;
  /** RegularExpression Id. */
  int BOOL_ASSIGNS = 26;
  /** RegularExpression Id. */
  int OUTPUTS = 27;
  /** RegularExpression Id. */
  int INTERNAL = 28;
  /** RegularExpression Id. */
  int GRAPH = 29;
  /** RegularExpression Id. */
  int PROPERTY = 30;
  /** RegularExpression Id. */
  int MARKING = 31;
  /** RegularExpression Id. */
  int NAME = 32;
  /** RegularExpression Id. */
  int MINF = 33;
  /** RegularExpression Id. */
  int MAXF = 34;
  /** RegularExpression Id. */
  int IDIV = 35;
  /** RegularExpression Id. */
  int FLOOR = 36;
  /** RegularExpression Id. */
  int CEIL = 37;
  /** RegularExpression Id. */
  int UNIFORM = 38;
  /** RegularExpression Id. */
  int NORMAL = 39;
  /** RegularExpression Id. */
  int EXPONENTIAL = 40;
  /** RegularExpression Id. */
  int GAMMA = 41;
  /** RegularExpression Id. */
  int LOGNORMAL = 42;
  /** RegularExpression Id. */
  int CHISQ = 43;
  /** RegularExpression Id. */
  int LAPLACE = 44;
  /** RegularExpression Id. */
  int CAUCHY = 45;
  /** RegularExpression Id. */
  int RAYLEIGH = 46;
  /** RegularExpression Id. */
  int POISSON = 47;
  /** RegularExpression Id. */
  int BINOMIAL = 48;
  /** RegularExpression Id. */
  int BERNOULLI = 49;
  /** RegularExpression Id. */
  int BITNOT = 50;
  /** RegularExpression Id. */
  int BITOR = 51;
  /** RegularExpression Id. */
  int BITAND = 52;
  /** RegularExpression Id. */
  int BITXOR = 53;
  /** RegularExpression Id. */
  int INT = 54;
  /** RegularExpression Id. */
  int BOOL = 55;
  /** RegularExpression Id. */
  int BIT = 56;
  /** RegularExpression Id. */
  int RATE = 57;
  /** RegularExpression Id. */
  int VERIFY = 58;
  /** RegularExpression Id. */
  int SEARCH = 59;
  /** RegularExpression Id. */
  int ASSIGN = 60;
  /** RegularExpression Id. */
  int IMPLIC = 61;
  /** RegularExpression Id. */
  int COMMA = 62;
  /** RegularExpression Id. */
  int QMARK = 63;
  /** RegularExpression Id. */
  int EQUAL = 64;
  /** RegularExpression Id. */
  int OBRACE = 65;
  /** RegularExpression Id. */
  int LESSTHAN = 66;
  /** RegularExpression Id. */
  int BOOL_FALSE = 67;
  /** RegularExpression Id. */
  int BOOL_TRUE = 68;
  /** RegularExpression Id. */
  int AU = 69;
  /** RegularExpression Id. */
  int EU = 70;
  /** RegularExpression Id. */
  int EG = 71;
  /** RegularExpression Id. */
  int EF = 72;
  /** RegularExpression Id. */
  int AG = 73;
  /** RegularExpression Id. */
  int AF = 74;
  /** RegularExpression Id. */
  int PG = 75;
  /** RegularExpression Id. */
  int PF = 76;
  /** RegularExpression Id. */
  int PU = 77;
  /** RegularExpression Id. */
  int PX = 78;
  /** RegularExpression Id. */
  int Pr = 79;
  /** RegularExpression Id. */
  int Ss = 80;
  /** RegularExpression Id. */
  int OSQUARE = 81;
  /** RegularExpression Id. */
  int CSQUARE = 82;
  /** RegularExpression Id. */
  int GREATERTHAN = 83;
  /** RegularExpression Id. */
  int CBRACE = 84;
  /** RegularExpression Id. */
  int DISABLE = 85;
  /** RegularExpression Id. */
  int INF = 86;
  /** RegularExpression Id. */
  int SYMBOL = 87;
  /** RegularExpression Id. */
  int ID = 88;
  /** RegularExpression Id. */
  int NUM = 89;
  /** RegularExpression Id. */
  int INTEGER = 90;
  /** RegularExpression Id. */
  int REAL = 91;
  /** RegularExpression Id. */
  int LETTER = 92;
  /** RegularExpression Id. */
  int DIGIT = 93;
  /** RegularExpression Id. */
  int PLUS = 94;
  /** RegularExpression Id. */
  int MINUS = 95;
  /** RegularExpression Id. */
  int OPAR = 96;
  /** RegularExpression Id. */
  int CPAR = 97;
  /** RegularExpression Id. */
  int MULT = 98;
  /** RegularExpression Id. */
  int MOD = 99;
  /** RegularExpression Id. */
  int POWER = 100;
  /** RegularExpression Id. */
  int NOT = 101;
  /** RegularExpression Id. */
  int DIV = 102;
  /** RegularExpression Id. */
  int AND = 103;
  /** RegularExpression Id. */
  int OR = 104;
  /** RegularExpression Id. */
  int GEQ = 105;
  /** RegularExpression Id. */
  int LEQ = 106;
  /** RegularExpression Id. */
  int SEMICOLON = 107;
  /** RegularExpression Id. */
  int UNKNOWN = 108;
  /** RegularExpression Id. */
  int COMMENTS = 114;
  /** RegularExpression Id. */
  int DELIM = 115;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\".\"",
    "<ATACS>",
    "<END>",
    "<INPUTS>",
    "<INIT_STATE>",
    "<DUMMYS>",
    "<FAILTRANS>",
    "<VARIABLES>",
    "<INTEGERS>",
    "<NONINPS>",
    "<KEEPS>",
    "<ABSTRACTS>",
    "<CONTINUOUS>",
    "<RATES>",
    "<INITRATES>",
    "<INITVALS>",
    "<INITINTS>",
    "<INVARIANTS>",
    "<ENABLINGS>",
    "<ASSIGNS>",
    "<TRANS_RATES>",
    "<RATE_ASSIGNS>",
    "<INT_ASSIGNS>",
    "<DELAY_ASSIGNS>",
    "<PRIORITY_ASSIGNS>",
    "<BOOL_ASSIGNS>",
    "<OUTPUTS>",
    "<INTERNAL>",
    "<GRAPH>",
    "<PROPERTY>",
    "<MARKING>",
    "<NAME>",
    "\"min\"",
    "\"max\"",
    "\"idiv\"",
    "\"floor\"",
    "\"ceil\"",
    "\"uniform\"",
    "\"normal\"",
    "\"exponential\"",
    "\"gamma\"",
    "\"lognormal\"",
    "\"chisq\"",
    "\"laplace\"",
    "\"cauchy\"",
    "\"rayleigh\"",
    "\"poisson\"",
    "\"binomial\"",
    "\"bernoulli\"",
    "\"NOT\"",
    "\"OR\"",
    "\"AND\"",
    "\"XOR\"",
    "\"INT\"",
    "\"BOOL\"",
    "\"BIT\"",
    "\"rate\"",
    "\"verify\"",
    "\"search\"",
    "\":=\"",
    "\"=>\"",
    "\",\"",
    "\"?\"",
    "\"=\"",
    "\"{\"",
    "\"<\"",
    "\"false\"",
    "\"true\"",
    "\"AU\"",
    "\"EU\"",
    "\"EG\"",
    "\"EF\"",
    "\"AG\"",
    "\"AF\"",
    "\"PG\"",
    "\"PF\"",
    "\"PU\"",
    "\"PX\"",
    "\"Pr\"",
    "\"St\"",
    "\"[\"",
    "\"]\"",
    "\">\"",
    "\"}\"",
    "\")d\"",
    "\"inf\"",
    "<SYMBOL>",
    "<ID>",
    "<NUM>",
    "<INTEGER>",
    "<REAL>",
    "<LETTER>",
    "<DIGIT>",
    "\"+\"",
    "\"-\"",
    "\"(\"",
    "\")\"",
    "\"*\"",
    "\"%\"",
    "\"^\"",
    "\"~\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\">=\"",
    "\"<=\"",
    "\";\"",
    "\"\\\\\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "<COMMENTS>",
    "<DELIM>",
  };

}
